export const path = {
	landing: "/",
	login: "/login",
	register: "/register",
	forgotPassword: "/forgot-password",
	terms: "/terms",
	privacy: "/privacy",
	// Rotas da aplicação (com Layout e Sidebar)
	app: "/app",
	dashboard: "/app",
	admin: "/app/admin-users",
	priorityOptimization: "/app/priority-optimization",
	settings: "/app/settings",
	operationalRoutes: "/app/operational-routes",
	operationalRoutesList: "/app/operational-routes-list",
	schedule: "/app/schedule",
	productivity: "/app/productivity",
	nonconformities: "/app/nonconformities",
	alerts: "/app/alerts",
	control: "/app/control",
	operatorsList: "/app/operators-list",
	blingIntegration: "/app/bling-integration",
	userCreation: "/app/user-creation",
	productManagement: "/app/product-management",
	// Novas rotas das ações rápidas
	reports: "/app/reports",
	analytics: "/app/analytics",
	teamManagement: "/app/team-management",
	scheduling: "/app/scheduling",
	dataSync: "/app/data-sync",
	products: "/app/products",
	// Rotas específicas de produtos por categoria
	productAccessory: "/app/products/accessory",
	productAviationPlug: "/app/products/aviation-plug",
	productHvc: "/app/products/hvc",
	productConnector: "/app/products/connector",
	productFuseRelayBox: "/app/products/fuse-relay-box",
	productTerminal: "/app/products/terminal",
	productRubberParts: "/app/products/rubber-parts",
	productBackshell: "/app/products/backshell",
	productManifolds: "/app/products/manifolds",
	productWireHarness: "/app/products/wire-harness",
	productPcbConnector: "/app/products/pcb-connector",
};
